spring.application.name=hy-all

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.datasource.url=jdbc:mysql://47.237.188.77:3306/wChina?serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=WaterChina@242526

spring.jackson.mapper.accept-case-insensitive-properties=true